package XProcessLogRE;

use strict;
use vars qw(@ISA @EXPORT @EXPORT_OK %EXPORT_TAGS $VERSION);
use Exporter;
$VERSION = 1.00;
@ISA = qw(Exporter);
@EXPORT = qw(%patterns);

%XProcessLogRE::patterns = (
    # applies to all languages - no general exceptions
    'all_special' => [
        [qr/\b\d+\s(?:failed|errors?)\b/i                         , qr/\b0+\s(?:failed|errors?)\b|error.h|^Win32\\SINGLE_SETUP - 1 error\(s\)|\[WARNING\]|GERRIT_CHANGE_SUBJECT|HEAD is now/i, undef],
        [qr/^Invalid solution configuration\b/                    , undef, undef],
    ],
    # applies to all languages - with general exceptions
    'all_general' => [
        # An error                                                , Except this               , End of description
        [qr/\s*\[javac\]\s.*\.java:\d+:/i                         , qr/\.java:\d+:\s*warning:/, qr/\s*\[javac\]\s*\^/],
        [qr/\s*\[javac\]\s\d*\. ERROR in .*\.java.*/i             , undef                     , qr/\s*\[javac\]\s----------/],
        [qr/\s*\[javac\]\s*#\s*An unexpected error has been detected/i, undef                 , qr/\s*\[javac\]\s*#\s*An error report/],
        [qr/\.cpp\(\d+\) : error /i                               , undef, undef],
        [qr/\.h\(\d+\) : error /i                                 , undef, undef],
        [qr/\.rc\(\d+\) : error /i                                , undef, undef],
        [qr/\.cs\(\d+,\d+\): error /i                             , undef, undef],
        [qr/:\d+ : error:\s/i                                     , undef, undef],
        [qr/:\d+: \#error\s/i                                     , undef, undef],
        [qr/:\d+: invalid\s/i                                     , undef, undef],
        [qr/:\d+: parse error\b/i                                 , undef, undef],
        [qr/:\d+: syntax error\b/i                                , undef, undef],
        [qr/:\d+: undefined reference to /                        , undef, undef],
        [qr/:\d+: \*\*\*/i                                        , undef, undef],
        [qr/Files are different \(/i                              , undef, undef],
        [qr/\(\d+\) : error:\s/i                                  , undef, undef],
        [qr/\*\*\* No targets specified and no makefile found\./i , undef, undef],
        [qr/\*\*\* missing  \`endif\'\./i                         , undef, undef],
        [qr/\*\*\* missing separator\./i                          , undef, undef],
        [qr/\*\*\* missing separator\b/i                          , undef, undef],
        [qr/\<expression error\>/i                                , undef, undef],
        [qr/\<invalid operator\>/i                                , undef, undef],
        [qr/\] error:\s/i                                         , undef, undef],
        [qr/^make: \*\*\* \[.*\] Error \d+/i                      , undef, undef],
        [qr/: Can\'t find library:/                               , undef, undef],
        [qr/ Error \d+ /                                          , qr/\[CLEANINSTALLSTARTER\]|\[CLEANBOOTAPPS60\]/, undef],
        [qr/\berror \d+: missing file\b/i                         , undef, undef],
        [qr/\b(file|directory).*not found\b/i                     , qr/\sinfo:/i, undef],
        [qr/\bargument \d+ is invalid\b/i                         , undef, undef],
        [qr/\[\w+\]\s*\bbuild failed\b/i                          , undef, qr/\[\w+\]\s*$/],
        [qr/\bbuild failed\b/i                                    , undef, undef],
        [qr/^[^\]]*\.xml:\d+:\s.+/i                               , qr/ returned: 13| The following error occurred while executing this line| Compile failed; see the compiler error output for details/, undef],
        [qr/\bcannot find or open library file/i                  , undef, undef],
        [qr/\bcannot remove directory\b/i                         , undef, undef],
        [qr/\bcannot resolve symbol\b/i                           , undef, undef],
        [qr/\bcatastrophic error\b/i                              , undef, undef],
        [qr/\bcommand not found\b/i                               , qr/libxml.+(?:aclocal|automake|autoconf)/i, undef],
        [qr/\bcommand[ -]line error\b/i                           , undef, undef],
        [qr/\bcompilation aborted\b/i                             , undef, undef],
        [qr/\bcompile failed\b/i                                  , qr/.*\.xml:\d+: Compile failed; see the compiler error output for details\./, undef],
        [qr/\bconfigure: error:/i                                 , undef, undef],
        [qr/\bconflicting types for\b/i                           , undef, undef],
        [qr/\bdoes not exist\b/i                                  , qr/\[javac\] \[JLin\] .+\$\{compiler\.bootclasspath\}\" does not exist and will be ignored\.$|\bdoes not exist, re|Will create one\.|\[uptodate\]|info \w+ classpath entry|SASSERTMSG|\bdoes not exist, creating it now\.|\[delete\] Directory does not exist:|\[INFO\]|\[warn\]|\[subant\]|println/i, undef],
        [qr/\berror : .* failed\./i                               , undef, undef],
        [qr/\berror result returned from\b/i                      , undef, undef],
        [qr/\berror: failed\b/i                                   , undef, undef],
        [qr/\bfailed to copy\b/i                                  , undef, undef],
        [qr/\bfailed with message\b/i                             , undef, undef],
        [qr/\bfatal error\b/i                                     , qr/C1189: #error:  "Not |libs\\regex\\build\\has_icu_test.cpp/, undef],
        [qr/\binsufficient memory\b/i                             , undef, undef],
        [qr/\binternal error\b/i                                  , qr/\("Internal error"\)/, undef],
        [qr/\binvalid \w+ file name\b/i                           , undef, undef],
        [qr/\binvalid configuration\b/i                           , undef, undef],
        [qr/\binvalid conversion from\b/i                         , undef, undef],
        [qr/\blicense server not found\b/i                        , undef, undef],
        [qr/\bline \d+: syntax error\b/i                          , undef, undef],
        [qr/\bline\s+d+\s*:\s*error:\s/i                          , undef, undef],
        [qr/\bno rule to make target\b/i                          , qr/INSTALLSTARTER\.GCCE|BOOTAPPS60\.GCCE/, undef],
        [qr/\bno such file\b/i                                    , qr/INSTALLSTARTER\.GCCE:|BOOTAPPS60\.GCCE:|libs\\regex\\build\\has_icu_test.cpp/, undef],
        [qr/\bnot recognized as an internal or external command\b/i, undef, undef],
        [qr/\bpath name does not exist\b/i                        , undef, undef],
        [qr/\bproject.*failed to open\b/i                         , undef, undef],
        [qr/\breturned \d+ exit status\b/i                        , qr/\breturned 0+ exit status\b/i, undef],
        [qr/\bsyntax error at line\b/i                            , undef, undef],
        [qr/\bthe following error occurred\b/i                    , undef, undef],
        [qr/\bthe parameter or environment lists are too long/i   , undef, undef],
        [qr/\btoo many error messages\b/i                         , undef, undef],
        [qr/\btype specification for \w+ invalid\b/i              , undef, undef],
        [qr/\bunknown argument\b/i                                , undef, undef],
        [qr/\buses the undefined class\b/i                        , undef, undef],
        [qr/\|Failed\..+\|/i                                      , undef, undef],
        [qr/\|File \".+\|/i                                       , undef, undef],
        [qr/^\"\w+\.\w+\", line \d+\.\d+: \d+\-\d+ \(S\)/i        , undef, undef],
        [qr/^Error occurred during initialization of VM/i         , undef, undef],
        [qr/^Exception in thread/i                                , undef, undef],
        [qr/^Project.+failed to open.make/i                       , undef, undef],
        [qr/^[a-z.]+: error \w+:\s/i                              , undef, undef],
        [qr/^\[idcard2wix\].*: Error:/i                           , undef, undef],
        [qr/ERROR: a dependency loop exists/i                     , undef, qr/end dependency loop./],
        [qr/^\s*error before\b/i                                  , undef, undef],
        [qr/^\s*error\s?:\s/i                                     , qr/error:\s+\%1/, undef],
        [qr/\serror\s?:\s/i                                       , qr/\bSASSERTMSG\b|Error\s*\(\s*"|printf\s*\(\s*"|Stop\s*at\s*first|info:\s*error\s?:\s|\s+echo ERROR:\s+/i, undef],
        [qr/\: error C/i                                          , undef, undef],
        [qr/^error\s+C/i                                          , undef, undef],
        [qr/^\[error\]\s+Error\s+\d+/i                            , undef, undef],
        [qr/ Errcode 138: /i                                      , undef, undef],
        [qr/^ld: fatal:/                                          , undef, undef],
        [qr/^make: \[[^]]*?\] Error \d+/i                         , undef, undef],
        [qr/rm: cannot lstat/i                                    , undef, undef],
        [qr/The system cannot find the file specified\./i         , undef, undef],
        [qr/syntax error near unexpected token/i                  , undef, undef],
        [qr/command not found/i                                   , undef, undef],
        [qr/^\*\*\* wait: No child processes\.  Stop\./i          , undef, undef],
        [qr/^\*\*\* Waiting for unfinished jobs\.\.\.\./i         , undef, undef],
        [qr/^Access denied/i                                      , undef, undef],
        [qr/ld: cannot find /i                                    , undef, undef],
        [qr/^ld: warning: Symbol referencing errors/i             , undef, undef],
        [qr/^\[light\] light\.exe : error LGHT\d+ /i              , undef, undef],
        [qr/\|Exception./i                                        , undef, undef],
        [qr/does not represent a strongly named assembly$/i       , undef, undef],
        [qr/^Unable to create directory/i                         , undef, undef],
        [qr/^File creation error/i                                , undef, undef],
        [qr/Missing include nodes for wildcard grab/i             , undef, undef],
        [qr/OutOfMemoryError/i                                    , qr/OutOfMemoryError\.class|HeapDumpOnOutOfMemoryError|MAVEN_OPTS/i, undef],
        [qr/^\[error\]/i                                           , undef, undef],
        [qr/: No context called/i                                 , undef, undef],
        [qr/^java.lang.NoClassDefFoundError/i                     , undef, undef],
        [qr/problems with insufficient memory/i                   , undef, undef],
        [qr/\[sourceanalyzer\]\s+\[error\]/i                      , undef, undef],
        [qr/line\s+\d+\.\d+:\s*\d+-\d+\s*\(S\)/i                  , undef, undef],
        [qr/test failed/i                                         , undef, undef],
        [qr/Connection timed out/i                                , undef, undef],
        [qr/<error message=/i                                     , undef, qr/<\/error>/i],
        [qr/<failure message=/i                                   , undef, qr/<\/failure>/i],
        [qr/:ERROR:/i                                             , qr/ISubsystem::Error::Error/i, undef],
        [qr/Error 153: No objectModel tags found in deployment unit/i, undef, undef],
        [qr/The network connection could not be found\./i         , undef, undef],
        [qr/Error 157: Value \"neutral\" for attribute \"objectModel\" disallows architecture-specific platform conditions \(64bit\) within the idcard/i, undef, undef],
        [qr/This application has requested the Runtime to terminate it in an unusual way/i, undef, undef],
        [qr/mv: cannot move/i                                    , undef, undef],
        [qr/Inventory not found/i                                , undef, undef],
        [qr/SQLException:/                                       , undef, undef],
        [qr/JsqlFC:\s*\d+\s*DIFFERENT:/i                         , undef, undef],
        [qr/JsqlFC:\s*test\s+done\s+with\s+statusOK\s+false/i    , undef, undef],
        [qr/\*\*\*\s+FAILED\s+\*\*\*/                            , undef, undef],
        [qr/<result>false<\/result>/                             , undef, undef],
        [qr/<result>fail<\/result>/                              , undef, undef],
        [qr/Specified file could not be found/i                  , undef, undef],
        [qr/Failed to deploy artifacts/i                         , undef, undef],
        [qr/\[DOTX008W\]\[WARN\]/i                               , undef, undef],
        [qr/\[DOTJ021W\]\[WARN\]/i                               , undef, undef],
        [qr/\[DOTX008E\]\[ERROR\]/i                              , undef, undef], 
        [qr/Graphic file is not found/i                          , undef, undef],
        [qr/error: The following untracked working tree files would be overwritten by checkout:/i, undef, undef],
        [qr/^CMake Error at/                                     , undef, undef],
        [qr/Unable to match deployment unit/i                    , undef, undef],
        [qr/fatal: Unable to create/i                            , undef, undef],
        [qr/^An error has occured while processing artifact/i    , undef, undef],
        [qr/\[junit\]\sTEST\s.+?\sFAILED$/                       , undef, undef],
        [qr/\*\*\*Failed\s+\d+\.\d+\s+sec/                       , undef, undef],
        #Detection of clean errors:
        [qr/The path .* is too long\./                           , undef, undef],
        [qr/ - The directory is not empty\./                     , undef, undef],
        [qr/\bcp: closing .* A remote host did not respond within the timeout period\./i , undef, undef],
        [qr/ : error LNK\d+: /                                   , undef, undef],
        [qr/npm ERR!/                                            , undef, undef],
#        [qr/Errors detected:\s*[^\s0]/i                          , undef, undef],
#        [qr/\[xslt\]\s*\[.+?\]\s*\[ERROR\]/i                     , undef, undef],
#        [qr/org\.xml\.sax\.SAXParseException:\s+/i               , undef, undef],
    ],
    # applies to default
    'default' => [
    ],
);

1; 
